tutorial_practice/config/urls.py
from django.conf.urls import url
from django.contrib import admin

from polls.views import index, detail, vote

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name= 'index'),
    url(r'^polls/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^polls/(?P<pk>\d+)/vote/$', vote, name='vote')
]

tutorial_practice/polls/models.py
from django.db import models


class Question(models.Model):
    title = models.CharField(max_length=20)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Choice(models.Model):
    question = models.ForeignKey(Question)
    title = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title} ({self.question.title})'

tutorial_practice/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from polls.models import Question, Choice


def index(request):
    questions = Question.objects.all()
    context = {
        'questions': questions,
    }
    return render(request, 'polls/index.html', context)


def detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context)


def vote(request, pk):
    if request.method == 'POST':
        question = Question.objects.get(pk=pk)
        choice_pk = request.POST['vote']
        choice = Choice.objects.get(pk=choice_pk)
        choice.votes += 1
        choice.save()
        return redirect('detail', pk=question.pk)
    else:
        return HttpResponse('Permission denied')

tutorial_practice/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}설문{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

tutorial_practice/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %}
    상세
{% endblock %}
{% block content %}
    <h2>{{ question.title }}</h2>
    <form action="{% url 'vote' pk=question.pk %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <div class="radio">
                <label>
                    <input type="radio" name="vote" value="{{ choice.pk }}">
                    {{ choice.title }}
                    {{ choice.votes }}
                </label>
            </div>
        {% endfor %}
        <input type="submit" value="투표하기">
    </form>
{% endblock %}

tutorial_practice/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>설문리스트</h1>
    {% if questions %}
        {% for question in questions %}
            <div>
                <tr>
                    <td>
                        <a href="{% url 'detail' pk=question.pk %}">{{ question.title }}</a>
                    </td>
                </tr>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}